package io.openems.edge.growatt.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.growatt.GrowattConstants;

@ObjectClassDefinition(//
		name = "Growatt SPH Charger", //
		description = "Implements one PV string (MPPT port) of a Growatt SPH hybrid inverter.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "charger0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "PV port", description = "Which MPPT port of the inverter is read by this Charger?")
	PvPort pvPort() default PvPort.PV_1;

	@AttributeDefinition(name = "Growatt ESS-ID", description = "ID of the Growatt SPH ESS.")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "Growatt ESS target filter", description = "This is auto-generated by 'Growatt ESS-ID'.")
	String ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default GrowattConstants.DEFAULT_UNIT_ID;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Growatt SPH Charger [{id}]";
}
