package io.openems.edge.saj.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.startstop.StartStopConfig;
import io.openems.edge.saj.SajConstants;
import io.openems.edge.saj.common.enums.ControlMode;

@ObjectClassDefinition(//
		name = "SAJ CH2 ESS", //
		description = "Implements the SAJ CH2 commercial hybrid inverter as Energy Storage System.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;

	@AttributeDefinition(name = "Control mode", description = "INTERNAL leaves the schedule to the inverter. REMOTE_INVERTER dispatches the AC power of the inverter (register 0x8402), REMOTE_BATTERY the battery power (register 0x8405).")
	ControlMode controlMode() default ControlMode.INTERNAL;

	@AttributeDefinition(name = "Rated power [W]", description = "Nominal power of the inverter; the remote EMS Set-Point is a percentage of this value.")
	int ratedPower() default 50_000;

	@AttributeDefinition(name = "Capacity [Wh]", description = "Usable energy content of the battery.")
	int capacity() default 100_000;

	@AttributeDefinition(name = "Max battery charge power [W]", description = "Nominal charge power of the battery.")
	int maxBatteryChargePower() default 50_000;

	@AttributeDefinition(name = "Max battery discharge power [W]", description = "Nominal discharge power of the battery.")
	int maxBatteryDischargePower() default 50_000;

	@AttributeDefinition(name = "Minimum State-of-Charge [%]", description = "Below this State-of-Charge no discharge power is allowed.")
	int minSoc() default 10;

	@AttributeDefinition(name = "Maximum State-of-Charge [%]", description = "Above this State-of-Charge no charge power is allowed.")
	int maxSoc() default 100;

	@AttributeDefinition(name = "EMS keep-alive timeout [s]", description = "Value for register 0x8401 'EMSKeepTime'. If OpenEMS stops writing Set-Points for longer than this, the inverter falls back to its own application mode.")
	int emsKeepTime() default 60;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default SajConstants.DEFAULT_UNIT_ID;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "SAJ CH2 ESS [{id}]";
}
