package io.openems.edge.sungrow.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.startstop.StartStopConfig;
import io.openems.edge.sungrow.SungrowConstants;
import io.openems.edge.sungrow.common.enums.ControlMode;

@ObjectClassDefinition(//
		name = "Sungrow SH ESS", //
		description = "Implements the Sungrow SH series of hybrid inverters (e.g. SH20T) as Energy Storage System.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;

	@AttributeDefinition(name = "Control mode", description = "INTERNAL leaves the dispatch to the inverter. REMOTE_COMPULSORY uses EMS mode 2 and is verified in the field. REMOTE_EXTERNAL_EMS (mode 3) and REMOTE_VPP (mode 4) additionally require the heartbeat.")
	ControlMode controlMode() default ControlMode.INTERNAL;

	@AttributeDefinition(name = "Capacity [Wh]", description = "Usable energy content of the battery.")
	int capacity() default 25_000;

	@AttributeDefinition(name = "Max apparent power [VA]", description = "Nominal apparent power of the inverter; 20000 for a SH20T.")
	int maxApparentPower() default 20_000;

	@AttributeDefinition(name = "Max battery charge power [W]", description = "Maximum charge power of the battery; also written to Holding-Register 33046.")
	int maxBatteryChargePower() default 20_000;

	@AttributeDefinition(name = "Max battery discharge power [W]", description = "Maximum discharge power of the battery; also written to Holding-Register 33047.")
	int maxBatteryDischargePower() default 20_000;

	@AttributeDefinition(name = "Minimum State-of-Charge [%]", description = "Below this State-of-Charge no discharge power is allowed.")
	int minSoc() default 10;

	@AttributeDefinition(name = "Maximum State-of-Charge [%]", description = "Above this State-of-Charge no charge power is allowed.")
	int maxSoc() default 100;

	@AttributeDefinition(name = "External EMS heartbeat [s]", description = "Value for Holding-Register 13079. Only used with REMOTE_EXTERNAL_EMS and REMOTE_VPP: if OpenEMS stops writing for longer than this, the inverter returns to self-consumption mode.")
	int externalEmsHeartbeat() default 60;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default SungrowConstants.DEFAULT_UNIT_ID;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Sungrow SH ESS [{id}]";
}
