package io.openems.edge.growatt.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.startstop.StartStopConfig;
import io.openems.edge.growatt.GrowattConstants;
import io.openems.edge.growatt.common.enums.ControlMode;

@ObjectClassDefinition(//
		name = "Growatt SPH ESS", //
		description = "Implements the Growatt SPH hybrid inverter as Energy Storage System.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Start/stop behaviour?", description = "Should this Component be forced to start or stop?")
	StartStopConfig startStop() default StartStopConfig.AUTO;

	@AttributeDefinition(name = "Control mode", description = "INTERNAL leaves the schedule to the inverter. REMOTE lets OpenEMS control priority mode and power rates; this is required for Virtual-Power-Plant operation.")
	ControlMode controlMode() default ControlMode.INTERNAL;

	@AttributeDefinition(name = "Capacity [Wh]", description = "Usable energy content of the battery.")
	int capacity() default 6000;

	@AttributeDefinition(name = "Max apparent power [VA]", description = "Nominal apparent power of the inverter; 4600 for a SPH4600.")
	int maxApparentPower() default 4600;

	@AttributeDefinition(name = "Max battery charge power [W]", description = "Nominal charge power of the battery. Used to convert a power Set-Point into the Growatt power rate.")
	int maxBatteryChargePower() default 4600;

	@AttributeDefinition(name = "Max battery discharge power [W]", description = "Nominal discharge power of the battery. Used to convert a power Set-Point into the Growatt power rate.")
	int maxBatteryDischargePower() default 4600;

	@AttributeDefinition(name = "Minimum State-of-Charge [%]", description = "Below this State-of-Charge no discharge power is allowed.")
	int minSoc() default 10;

	@AttributeDefinition(name = "Maximum State-of-Charge [%]", description = "Above this State-of-Charge no charge power is allowed.")
	int maxSoc() default 100;

	@AttributeDefinition(name = "BDC rated power [W]", description = "Reference power for the VPP remote power percentage. 0 reads the value from the inverter (VPP register 30026).")
	int bdcRatedPower() default 0;

	@AttributeDefinition(name = "EMS failure time [s]", description = "VPP watchdog (register 30203/30204): time without EMS communication until the inverter falls back to its own schedule. 0 disables the watchdog.")
	int emsFailureTime() default 60;

	@AttributeDefinition(name = "Power rate step [%]", description = "Quantization of the calculated power rate. Bigger steps cause fewer writes to the non-volatile memory of the inverter.")
	int powerRateStep() default 5;

	@AttributeDefinition(name = "Minimum write interval [s]", description = "Minimum time between two Set-Point writes. Protects the non-volatile memory of the inverter.")
	int minimumWriteInterval() default 30;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default GrowattConstants.DEFAULT_UNIT_ID;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Growatt SPH ESS [{id}]";
}
